name: Basic pipeline with automated build and test stages Project

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
      - run: npm run build
